import '../styles/globals.css';
import PrimaryLayout from '@/components/layout/PrimaryLayout';
import type { AppProps } from 'next/app';
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <PrimaryLayout>
      <Head>
        <title>Hillary&apos;s Cook Book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/chef-logo.png" />
      </Head>
      <Component {...pageProps} />
    </PrimaryLayout>
  );
}
